apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "raffa-qrs"
  description: "raffa-qrs"
  tags:
    - java
    - quarkus
  links:
    - url: https://devspaces.apps.control-cluster-raffa.demo.red-chesterfield.com/#https://github.com/raf-backstage-demo/raffa-qrs?che-editor=che-incubator/che-code/insiders&devfilePath=.devfilev2-vscode.yaml
      title: CodeReady Workspaces (VS Code)
      icon: web    
    - url: https://devspaces.apps.control-cluster-raffa.demo.red-chesterfield.com/#https://github.com/raf-backstage-demo/raffa-qrs?che-editor=che-incubator/che-idea/next&devfilePath=.devfilev2-intellij.yaml
      title: CodeReady Workspaces (JetBrains IntelliJ)
      icon: web
    - url: https://grafana-route-user-workload-grafana.apps.control-cluster-raffa.demo.red-chesterfield.com/d/AqEG4weWk/error-budget?orgId=1&refresh=5s&var-virtual_service=raffa-qrs-stable.myapp2-prod.svc.cluster.local&var-time_interval=1h&var-SLO=95&var-latency=1000
      title: SRE Metrics (production)
      icon: web
  annotations:
    'github.com/project-slug': raf-backstage-demo/raffa-qrs
    'backstage.io/kubernetes-id': raffa-qrs
    'backstage.io/techdocs-ref': dir:.
    'sonarqube.org/project-key': raf-backstage-demo_raffa-qrs
    'prometheus.io/alert': ErrorBudgetBurn-critical-myapp2-prod-raffa-qrs,ErrorBudgetBurn-warning-myapp2-prod-raffa-qrs
    'prometheus.io/rule': virtual_service:myapp2_prod_raffa-qrs:error_rate_1d,virtual_service:myapp2_prod_raffa-qrs:error_rate_1h,virtual_service:myapp2_prod_raffa-qrs:error_rate_2h,virtual_service:myapp2_prod_raffa-qrs:error_rate_30m
spec:
  type: service
  lifecycle: experimental
  owner: "demo-team-b"
  system: system:myapp2